### ISSUE TITLE
Pflichtenheft konkretisieren

### ISSUE THREAD

**Issue by cherry13579** [HenFo/Geosoftware-II-AALLH#25]
Zielbestimmung (Anika, Lia)

- [x] Welcher Geodatenkatalog wird verwendet
- [x] Wunschkriterien prüfen, ob es nicht doch verpflichtende Kriterien sind
- [x] Hochladen oder Erstellen von Geodatensätzen?
- [x] Den Nutzer mehr konkretisieren
- [x] Free and Open Software Source ?? überprüfen
- [x] Welche Geodatenkataloge werden genutzt 
- [x] Genau beschreiben, warum diese FUnktion von Nutzen für die späteren Anwender ist
- [x] Warum verbessern "Datenerhalter" den Zugang?
- [x] Warum kann man das Programm nicht vom Laptop oder Handy aus benutzten?

Funktionale Anforderungen (Alle)
- [x]  Über dern Begriff  "Extraction" nachdenken, einheitlichen Begriff verwenden
- [x] KONKRETER werden , nicht nur wiedergeben des Lastenheftes
- [x] Wie genau wollen wir die einzelnen Funktionen lösen
- [x] FU001 Auf welcher Seite? Wie machen wir die UI? Genau erklären, wie es gemacht wird ( "Darf nicht eingebunden werden ist zu unkonkret"
- [x] Bonuseigenschaft ausführlicher (Mock-up?, Mapping-Framework)

Produktleistungen (Aysel)
- [x] Wie testen und belegen
- [x] Test und Belegung wie dokumentieren? ("Best Practise?)

Testdaten (Lukas) 

- [x] konkreter werden, mehr Datensätze pro Format 
- [x] Datenquellen mehr konkretisieren nicht nur rüberkopieren 

Nicht-fuktionale Anforderungen (Aysel)

- [x] Invitation toBit danach durchsuchen und eintragen

Produktumgebung (Henry)

- [x] Versionsnummern
- [x] CLI Einfügen
- [x] Lizenze unter denen wir veröffentlichen wollen aufschreiben
- [x] Auf welcher Plattform wollen wir unseren Code verwalten

Zeitplan  (Anika,Lia)

- [x] Wie wollen wir mit Problemen umgehen
- [x] iteratives Vorgehen?? Oder Nicht??
- [x] Arbeitetn wir  über die Feiertage?
- [x] Wie lange werden die verschiedenen Aufgaben dauern?

**Comment by Anika2** [comment]
Pflichtenheft neue Aufteilung: 

API Endpunkte: Aysel, Anika
Musskriterien: Anika 
Testdaten: Lukas 
Produktumgebung: Henry
Bonusfeature: Lia
